# Generated by Django 4.2.4 on 2023-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team', max_length=1000),
        ),
    ]
