# Generated by Django 4.2.4 on 2023-09-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_team_captain_team_size_alter_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='form_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='form_url',
        ),
    ]
